export const CERT_LIST_REQUEST = 'CERT_LIST_REQUEST'
export const CERT_LIST_SUCCESS = 'CERT_LIST_SUCCESS'
export const CERT_LIST_FAIL = 'CERT_LIST_FAIL'

export const CERT_CREATE_REQUEST = 'CERT_CREATE_REQUEST'
export const CERT_CREATE_SUCCESS = 'CERT_CREATE_SUCCESS'
export const CERT_CREATE_FAIL = 'CERT_CREATE_FAIL'

export const CERT_UPDATE_REQUEST = 'CERT_UPDATE_REQUEST'
export const CERT_UPDATE_SUCCESS = 'CERT_UPDATE_SUCCESS'
export const CERT_UPDATE_FAIL = 'CERT_UPDATE_FAIL'

export const CERT_DELETE_REQUEST = 'CERT_DELETE_REQUEST'
export const CERT_DELETE_SUCCESS = 'CERT_DELETE_SUCCESS'
export const CERT_DELETE_FAIL = 'CERT_DELETE_FAIL' 

export const ADMIN_SEARCH_CERT_REQUEST = 'ADMIN_SEARCH_CERT_REQUEST'
export const ADMIN_SEARCH_CERT_SUCCESS = 'ADMIN_SEARCH_CERT_SUCCESS'
export const ADMIN_SEARCH_CERT_FAIL = 'ADMIN_SEARCH_CERT_FAIL'